# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.20.2'

target 'CBieng' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CBieng

  target 'CBiengTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CBieng-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CBieng-tvOS

  target 'CBieng-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
