# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.20.2'
pod 'Firebase/Auth', '~> 5.20.2'

target 'CBieng' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CBieng
end
