# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build a new dev release"
  lane :dev do
    build("dev")
  end

  desc "Build a new prod release"
  lane :prod do
    build("prod")
  end
end

def build(flavor)
  gradle(
    task: "assemble",
    build_type: "Release",
    flavor: flavor.capitalize,
    properties: {
      "versionCode": number_of_commits
    },
    flags: "--no-daemon"
  )
end

def changelog
  changelog_from_git_commits(commits_count: 1)
  changelog = lane_context[SharedValues::FL_CHANGELOG]
  branch = git_branch
  if branch == "master" || branch == "origin/master"
    return "Master:\n#{changelog}"
  else
    return "Build for branch \"#{branch}\":\n#{changelog}"
  end
end